name: flutter_form_craft
description: The FormCraft package simplifies form management in Flutter applications, providing a convenient set of utilities for building and interacting with forms.
version: 0.0.1
homepage: https://github.com/Spriggan1992/flutter_form_craft/blob/main/README.md
repository: https://github.com/Spriggan1992/flutter_form_craft

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
